draw_set_color(c_black)
draw_set_alpha(.8)
draw_rectangle(0, 0, room_width, room_height, 0)
draw_set_color(c_white)
draw_set_alpha(1)

draw_set_font(Font2)
draw_set_halign(fa_center)
draw_set_valign(fa_center)
draw_text(room_width/2, room_height/2 - 30, "GAME OVER")
draw_set_font(Font3)
draw_text(room_width/2, room_height/2 + 30, "PRESS 'R' TO RESTART")
draw_set_halign(-1)
draw_set_valign(-1)
draw_set_font(-1)